### ISSUE TITLE
Support custom @Generated annotation

### ISSUE THREAD

**Issue by josephearl** [ciscoo/cxf-codegen-gradle#105]
The `@Generated` annotation added has source retention so does not work with tools like JaCoCo for excluding generated code from code coverage reports.

Support specifying a custom generated annotation class so that users can create a generated annotation that is retained in the class file for use with tools like JaCoCo.

**Comment by ciscoo** [comment]
This plugin does not participate in the code generation process. It provides a Gradle task that delegates the code generation to the `wsdl2java` tool from the Apache CXF project: https://cxf.apache.org/docs/wsdl-to-java.html

Recommend you report the issue or request such functionality to their issue tracker: https://issues.apache.org/jira/projects/CXF/issues/
