### ISSUE TITLE
Gradle plugin portal does not show latest version

### ISSUE THREAD

**Issue by josephearl** [ciscoo/cxf-codegen-gradle#106]
https://plugins.gradle.org/plugin/io.mateo.cxf-codegen - latest version listed is 1.2.1

**Comment by ciscoo** [comment]
As of https://github.com/ciscoo/cxf-codegen-gradle/issues/81, the plugin is no longer published to the Gradle plugin portal. This is also called out in the last release to the portal:


> Version 1.2.1 (latest)
> 
> Created 23 April 2023.
> Gradle plugin to generate code sources from WSDL.
> **The next major version and subsequent versions will only be published to the Maven Central Repository.**

There is nothing I can do (as far as I'm aware) to fix the version mismatch. The portal proxies Maven Central by the way, so even if the portal doesn't list the version, you can still use a recent version if you have not configured Maven Central as a repository for your build environment.
