### ISSUE TITLE
Setting language/locale for generated javadoc comments

### ISSUE THREAD

**Issue by mikhail-timofeev** [ciscoo/cxf-codegen-gradle#20]
I could not find a way to specify the language used to generate javadoc comments in the generated classes and I think this would be a great feature to have. E.g. via a parameter 'locale' accepting java.util.Locale.

**Comment by ciscoo** [comment]
The plugin delegates to [`wsdl2java`](https://cxf.apache.org/docs/wsdl-to-java.html). The tool itself does not provide any option in relation to the language or locale as far as I can see, so this plugin does not either.

**Comment by mikhail-timofeev** [comment]
couldn't it be done like here?
https://github.com/yupzip/wsdl2java/blob/0eef05c057fd799aeec59c9cf057793ad4c73743/src/main/groovy/com/yupzip/wsdl2java/Wsdl2JavaTask.groovy#L64

**Comment by ciscoo** [comment]
Oh, I see. That plugin programmatically invokes the `wsdl2java` tool directly. This plugin does not do that and instead delegates the invocation to Gradle via [`JavaExec`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html):

* https://github.com/ciscoo/cxf-codegen-gradle/blob/v1.0.0-rc.3/cxf-codegen-gradle/src/main/java/io/mateo/cxf/codegen/CxfCodegenPlugin.java#L98...L105

As mentioned in the documentation, `Wsdl2JavaTask` is a subclass of `JavaExec`, so whatever you can do to `JavaExec` tasks you can do to `Wsdl2JavaTask`

From Googling, there are two ways to set the locale.

1. Programmatically as that plugin you linked does.
2. JVM arguments.

You should be able to do (2) with something like following:

```kotlin
import io.mateo.cxf.codegen.wsdl2java.Wsdl2JavaTask

plugins {
    id("java")
    id("io.mateo.cxf-codegen") version "1.0.0-rc.3"
}

repositories {
    mavenCentral()
}

cxfCodegen {
    wsdl2java {
        register("calculator") {
            wsdl.set(file("calculator.wsdl"))
        }
    }
}

tasks.named("wsdl2javaCalculator", Wsdl2JavaTask::class) {
    allJvmArgs = listOf("-Duser.language=fr", "-Duser.country=CA")
}
```

References:

* https://www.oracle.com/technical-resources/articles/javase/locale.html#using
* https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html

**Comment by mikhail-timofeev** [comment]
will try that right away, thank you for your support and work!
