### ISSUE TITLE
Caching and deprecated JavaExec

### ISSUE THREAD

**Issue by iamceph** [ciscoo/cxf-codegen-gradle#24]
Hello, I found out that your plugin still uses deprecated JavaExec in Gradle 7.3. Is there any way to get rid of it?
![image](https://user-images.githubusercontent.com/4377405/146780050-ac290b44-8ef0-4a16-96ac-59f2ad93b5a6.png)

I also wanted to ask if there is any possibility to add support for Caching. 

Thank you in advance.

**Comment by ciscoo** [comment]
The deprecation issue was taken care as part of https://github.com/ciscoo/cxf-codegen-gradle/issues/10, specifically https://github.com/ciscoo/cxf-codegen-gradle/commit/a3cb88a5d041673d15b0fcbeca3b47130663b290.

As for caching, is there something your build scans are showing that is leading to the tasks not being cached? There are some changes made from https://github.com/ciscoo/cxf-codegen-gradle/issues/12, but curious if there is anything that was missed.

**Comment by iamceph** [comment]
Thank you for your response!

I was using the RC3 version, I will try latest snapshots and let you know.
