### ISSUE TITLE
Jakarta WS API with greather 3 version wsdl not generated

### ISSUE THREAD

**Issue by zhasulan** [ciscoo/cxf-codegen-gradle#47]
WSDL generated if only use old version of jakarta libs

`    cxfCodegen("jakarta.xml.ws:jakarta.xml.ws-api:2.3.3")
`
`
    cxfCodegen("jakarta.annotation:jakarta.annotation-api:1.3.5")
`

If we use new version of Jakarta WS API 3 or 4 versions wsdl generation return error:

`Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Service
`

**Comment by ciscoo** [comment]
This is expected due to the Apache CXF not supporting Jakarta yet.

See https://issues.apache.org/jira/browse/CXF-8371
