### ISSUE TITLE
Raise the minimum supported version of Java to 11

### ISSUE THREAD

**Issue by ciscoo** [ciscoo/cxf-codegen-gradle#56]
Apache CXF 4.0.0 requires Java 11 as a baseline: https://issues.apache.org/jira/browse/CXF-8660.

Therefore, this plugin will also require a Java 11 baseline.

**Comment by loicdesguin** [comment]
Hello, 
But in fact the plugin is not working using version > 11 (Version 17) has javax.xml.ws.Service is no more part of JDK. 

Do you have upgraded the tool ? 

Regards

**Comment by ciscoo** [comment]
@loicdesguin This is covered in the docs: https://ciscoo.github.io/cxf-codegen-gradle/docs/current/user-guide/#java-9
and is unrelated to this issue.

This issue is about building _this_ plugin with Java 11 which is different from the tool itself.

**Comment by ciscoo** [comment]
There is no benefit at the moment to making the plugin require Java 11.

**Comment by loicdesguin** [comment]
The request is not to have the tool requiring java 11 but having the tool working wirth recent version of Java what's a logical request: forcing people to keep working with java 8 is a non sens.
Marking my comment of topics will not solve the fact you tool is out of date.

I dropped this plugin and called directly CXF work perfectly and is making me thinking a plugin is useless.

Regards
